races:
 - human
 - dwarf
 - elf
 - halfling
 - orc
 - dragonkin
 - tiefling
 - gnome
 - kobold
 - beastmen
genders:
 - male
 - female
factions:
 - imperials
 - independents
 - pirates
 - cultists
 - seperatists
 - pacifists
 - thieves
 - mages
 - outcasts
 - merchants
 - believers in the one true scale